language: php

php:
  - 5.3.3
  - 5.4
  - 5.5

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install
    - mysql -e 'create database IF NOT EXISTS revpdf_test;'
    - pyrus install --force phpunit/DbUnit

script:
  - phpunit --configuration tests/vendor/travis/phpunit.travis.xml