<?php
namespace RevPDFLib\Tests;

use RevPDFLib\Items\Element\AbstractElement;

/**
 * Test class for AbstractElement.
 * Generated by PHPUnit on 2012-02-12 at 11:07:53.
 */
class AbstractElementTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AbstractElement
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = $this->getMockForAbstractClass('\RevPDFLib\Items\Element\AbstractElement', array(), '', false);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::getPosx
     * @todo Implement testGetPosx().
     */
    public function testGetPosx() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::setPosx
     * @todo Implement testSetPosx().
     */
    public function testSetPosx() {
        $this->object->setPosx(50);
        $this->assertEquals(50, $this->object->getPosx());
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::getPosy
     * @todo Implement testGetPosy().
     */
    public function testGetPosy() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::setPosy
     * @todo Implement testSetPosy().
     */
    public function testSetPosy() {
        $this->object->setPosy(100);
        $this->assertEquals(100, $this->object->getPosy());
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::getFont
     * @todo Implement testGetFont().
     */
    public function testGetFont() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::setFont
     * @todo Implement testSetFont().
     */
    public function testSetFont() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::isAutoExtend
     * @todo Implement testIsAutoExtend().
     */
    public function testIsAutoExtend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::setIsAutoExtend
     * @todo Implement testSetIsAutoExtend().
     */
    public function testSetIsAutoExtend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::getStyle
     * @todo Implement testGetStyle().
     */
    public function testGetStyle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::setStyle
     * @todo Implement testSetStyle().
     */
    public function testSetStyle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::getFontSize
     * @todo Implement testGetFontSize().
     */
    public function testGetFontSize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::setFontSize
     * @todo Implement testSetFontSize().
     */
    public function testSetFontSize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::getWidth
     * @todo Implement testGetWidth().
     */
    public function testGetWidth() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::setWidth
     * @todo Implement testSetWidth().
     */
    public function testSetWidth() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::getHeight
     * @todo Implement testGetHeight().
     */
    public function testGetHeight() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::setHeight
     * @todo Implement testSetHeight().
     */
    public function testSetHeight() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::getHeightOffset
     * @todo Implement testGetHeightOffset().
     */
    public function testGetHeightOffset() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::setHeightOffset
     * @todo Implement testSetHeightOffset().
     */
    public function testSetHeightOffset() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::getBorder
     * @todo Implement testGetBorder().
     */
    public function testGetBorder() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::setBorder
     * @todo Implement testSetBorder().
     */
    public function testSetBorder() {
        $this->object->setBorder('L');
        $this->assertEquals('L', $this->object->getBorder());
        $this->object->setBorder('LR');
        $this->assertEquals('LR', $this->object->getBorder());
        $this->object->setBorder('LRB');
        $this->assertEquals('LRB', $this->object->getBorder());
        $this->object->setBorder('LRBT');
        $this->assertEquals('LRBT', $this->object->getBorder());
        $this->object->setBorder('LRéBTAé');
        $this->assertEquals('LRBT', $this->object->getBorder());
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::getBorderWidth
     * @todo Implement testGetBorderWidth().
     */
    public function testGetBorderWidth() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::setBorderWidth
     * @todo Implement testSetBorderWidth().
     */
    public function testSetBorderWidth() {
        $this->object->setBorderWidth('1');
        $this->assertEquals('1', $this->object->getBorderWidth());
        $this->object->setBorderWidth('0.2');
        $this->assertEquals('0.2', $this->object->getBorderWidth());
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::getAlignment
     * @todo Implement testGetAlignment().
     */
    public function testGetAlignment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::setAlignment
     * @todo Implement testSetAlignment().
     */
    public function testSetAlignment() {
        $this->object->setAlignment('L');
        $this->assertEquals('L', $this->object->getAlignment());
        $this->object->setAlignment('C');
        $this->assertEquals('C', $this->object->getAlignment());
        $this->object->setAlignment('R');
        $this->assertEquals('R', $this->object->getAlignment());
        $this->object->setAlignment('Z');
        $this->assertEquals('L', $this->object->getAlignment());
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::getFillColor
     * @todo Implement testGetFillColor().
     */
    public function testGetFillColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::setFillColor
     * @todo Implement testSetFillColor().
     */
    public function testSetFillColor() {
        $this->object->setFillColor('FFF');
        $this->assertEquals('#FFF', $this->object->getFillColor());
        $this->object->setFillColor('#FFF');
        $this->assertEquals('#FFF', $this->object->getFillColor());
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::getFillStyle
     * @todo Implement testGetFillStyle().
     */
    public function testGetFillStyle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::setFillStyle
     * @todo Implement testSetFillStyle().
     */
    public function testSetFillStyle() {
        $this->object->setFillStyle('F');
        $this->assertEquals('F', $this->object->getFillStyle());
        $this->object->setFillStyle('D');
        $this->assertEquals('D', $this->object->getFillStyle());
        $this->object->setFillStyle('FD');
        $this->assertEquals('FD', $this->object->getFillStyle());
        $this->object->setFillStyle('FDX');
        $this->assertEquals('FD', $this->object->getFillStyle());
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::getTextColor
     * @todo Implement testGetTextColor().
     */
    public function testGetTextColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::setTextColor
     * @todo Implement testSetTextColor().
     */
    public function testSetTextColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::getFormat
     * @todo Implement testGetFormat().
     */
    public function testGetFormat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::setFormat
     * @todo Implement testSetFormat().
     */
    public function testSetFormat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::getType
     * @todo Implement testGetType().
     */
    public function testGetType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::setType
     * @todo Implement testSetType().
     */
    public function testSetType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::getValue
     * @todo Implement testGetValue().
     */
    public function testGetValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::setProperties
     * @todo Implement testSetProperties().
     */
    public function testSetProperties() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Items\Element\AbstractElement::writeContent
     * @todo Implement testWriteContent().
     */
    public function testWriteContent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
