<?php

namespace RevPDFLib\Tests;

use RevPDFLib\DependencyInjection\DiExtension;

/**
 * Test class for DiExtension.
 * Generated by PHPUnit on 2012-02-12 at 11:55:33.
 */
class DiExtensionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DiExtension
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DiExtension(dirname(__DIR__) . '/../../tmp/');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers RevPDFLib\DependencyInjection\DiExtension::getContainer
     * @todo Implement testGetContainer().
     */
    public function testGetContainer()
    {
        $this->assertTrue($this->object->getContainer() instanceof \Symfony\Component\DependencyInjection\ContainerBuilder);
    }

}
