<?php
namespace RevPDFLib\Tests;

use RevPDFLib\Writer\TfpdfWriter;

/**
 * Test class for TfpdfWriter.
 * Generated by PHPUnit on 2012-02-13 at 01:10:15.
 */
class TfpdfWriterTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var TfpdfWriter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TfpdfWriter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RevPDFLib\Writer\TfpdfWriter::setCurrentPosition
     * @todo Implement testSetCurrentPosition().
     */
    public function testSetCurrentPosition() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Writer\TfpdfWriter::getCurrentPosition
     * @todo Implement testGetCurrentPosition().
     */
    public function testGetCurrentPosition() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Writer\TfpdfWriter::getEndPosition
     * @todo Implement testGetEndPosition().
     */
    public function testGetEndPosition() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Writer\TfpdfWriter::setEndPosition
     * @todo Implement testSetEndPosition().
     */
    public function testSetEndPosition() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Writer\TfpdfWriter::setPageHeader
     * @todo Implement testSetPageHeader().
     */
    public function testSetPageHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Writer\TfpdfWriter::getPageHeader
     * @todo Implement testGetPageHeader().
     */
    public function testGetPageHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Writer\TfpdfWriter::getLeftMargin
     * @todo Implement testGetLeftMargin().
     */
    public function testGetLeftMargin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Writer\TfpdfWriter::getTopMargin
     * @todo Implement testGetTopMargin().
     */
    public function testGetTopMargin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RevPDFLib\Writer\TfpdfWriter::header
     * @todo Implement testHeader().
     */
    public function testHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
